"""
itinerary_tools.py
==================
LangChain tools for the ItineraryExecutorNode.
These tools are explicitly mapped to the step_types generated by the Planner.
"""
from __future__ import annotations

from typing import Optional
from langchain_core.tools import tool, ToolException

# Assuming these exist in your project as imported
from security import validate_city, validate_positive_number, validate_season
from tools.dependencies import data_provider


# ---------------------------------------------------------------------------
# ── Internal DB Fetchers ───────────────────────────────────────────────────
# ---------------------------------------------------------------------------

def _fetch_flights(origin: str, destination: str) -> list[dict]:
    """Fetch available flights between two cities (direct or connecting)."""
    origin = validate_city(origin)
    destination = validate_city(destination)
    direct_flights = data_provider.fetch_flights(origin, destination)
    
    has_direct = any("flight_number" in f for f in direct_flights)
    if not has_direct:
        connecting_flights = data_provider.find_connecting_flights(origin, destination)
        if connecting_flights and any("route" in f for f in connecting_flights):
            return connecting_flights
    return direct_flights


def _fetch_hotels(city: str) -> list[dict]:
    """Fetch all hotels for a given city."""
    city = validate_city(city)
    return data_provider.fetch_hotels(city)


def _fetch_activities(city: str) -> list[dict]:
    """Fetch all activities for a given city."""
    city = validate_city(city)
    return data_provider.fetch_activities(city)


def _fetch_weather(city: str) -> dict:
    """Fetch average seasonal weather for a city."""
    city = validate_city(city)
    return data_provider.get_average_weather(city, "Spring")  # Defaulting as per original


def _fetch_best_time(city: str) -> dict:
    """Fetch best time to visit."""
    city = validate_city(city)
    return data_provider.get_best_time_to_visit(city)


# ---------------------------------------------------------------------------
# ── LangChain Tools (Exposed to Executor) ──────────────────────────────────
# ---------------------------------------------------------------------------

@tool
def search_outbound_flights(origin: str, destination: str) -> list[dict]:
    """
    Search for available outbound flights from origin to destination.
    Returns a list of flights sorted cheapest first.
    """
    try:
        flights = _fetch_flights(origin, destination)
        available = []
        
        for f in flights:
            if "flight_number" in f:
                if str(f.get("availability", "")).lower() == "available":
                    available.append(f)
            elif "route" in f:
                # Handle connecting flight schema
                f["price"] = f.get("total_price", f.get("price", 9999)) 
                available.append(f)
                
        return sorted(available, key=lambda f: f.get("price", 9999))
    except Exception as e:
        raise ToolException(f"search_outbound_flights failed: {e}")


@tool
def search_return_flights(origin: str, destination: str) -> list[dict]:
    """
    Search for return flights (destination -> origin).
    Returns a list of flights sorted cheapest first.
    """
    try:
        # Reversing origin and destination for the return leg
        flights = _fetch_flights(destination, origin)
        available = []
        
        for f in flights:
            if "flight_number" in f:
                if str(f.get("availability", "")).lower() == "available":
                    available.append(f)
            elif "route" in f:
                f["price"] = f.get("total_price", f.get("price", 9999)) 
                available.append(f)
                
        return sorted(available, key=lambda f: f.get("price", 9999))
    except Exception as e:
        raise ToolException(f"search_return_flights failed: {e}")


@tool
def search_hotels(
    city: str,
    kosher_only: bool = False,
    max_price_per_night: Optional[float] = None,
    min_stars: Optional[int] = None,
) -> list[dict]:
    """
    Search hotels in a city, optionally filtered by price, stars, and amenities.
    Returns hotels sorted by stars (desc) then price (asc).
    """
    try:
        hotels = _fetch_hotels(city)
        
        if kosher_only:
            # Checking amenities list based on travel_db.json schema
            hotels = [
                h for h in hotels 
                if "kosher" in [a.lower() for a in h.get("amenities", [])]
            ]
        if min_stars:
            hotels = [h for h in hotels if h.get("stars", 0) >= min_stars]
        if max_price_per_night:
            hotels = [h for h in hotels if h.get("price_per_night", 9999) <= max_price_per_night]
            
        return sorted(hotels, key=lambda h: (-h.get("stars", 0), h.get("price_per_night", 9999)))
    except Exception as e:
        raise ToolException(f"search_hotels failed: {e}")


@tool
def search_activities(
    city: str,
    kosher_only: bool = False,
    vegetarian_friendly: bool = False,
    vegan_friendly: bool = False,
    category: Optional[str] = None,
    max_price: Optional[float] = None,
) -> list[dict]:
    """
    Search activities/attractions in a city.
    Returns activities mapped strictly to the database schema.
    """
    try:
        activities = _fetch_activities(city)

        if category:
            cat_lower = category.lower()
            activities = [
                a for a in activities
                if cat_lower in str(a.get("category", "")).lower()
            ]
        
        # Dietary filtering based on Executor parameters
        if kosher_only:
            activities = [a for a in activities if "kosher" in [am.lower() for am in a.get("amenities", [])] or "kosher" in str(a).lower()]
        if vegetarian_friendly:
            activities = [a for a in activities if "vegetarian" in str(a).lower()]
        if vegan_friendly:
            activities = [a for a in activities if "vegan" in str(a).lower()]

        if max_price is not None:
            activities = [a for a in activities if a.get("price", 9999) <= max_price]

        # Sorting by price as a fallback
        return sorted(activities, key=lambda a: a.get("price", 0))
    except Exception as e:
        raise ToolException(f"search_activities failed: {e}")


@tool
def get_weather(city: str) -> dict:
    """
    Get average seasonal weather for a city.
    Use this to understand what to expect during the trip.
    """
    try:
        return _fetch_weather(city)
    except Exception as e:
        raise ToolException(f"get_weather failed: {e}")


@tool
def calculate_trip_cost(
    flight_price: float,
    return_flight_price: float,
    hotel_price_per_night: float,
    trip_days: int,
    estimated_activities_budget: float,
    estimated_meals_budget_per_day: float,
) -> dict:
    """
    Calculate total estimated trip cost to verify against the user's budget.
    """
    try:
        validate_positive_number(flight_price)
        validate_positive_number(return_flight_price)
        validate_positive_number(hotel_price_per_night)
        validate_positive_number(trip_days)
        
        hotel_total = hotel_price_per_night * trip_days
        meals_total = estimated_meals_budget_per_day * trip_days
        
        total = (
            flight_price
            + return_flight_price
            + hotel_total
            + estimated_activities_budget
            + meals_total
        )
        return {
            "outbound_flight":  round(flight_price, 2),
            "return_flight":    round(return_flight_price, 2),
            "hotel_total":      round(hotel_total, 2),
            "activities_total": round(estimated_activities_budget, 2),
            "meals_total":      round(meals_total, 2),
            "grand_total":      round(total, 2),
        }
    except Exception as e:
        raise ToolException(f"calculate_trip_cost failed: {e}")


# ---------------------------------------------------------------------------
# ── Backward Compatibility Aliases ─────────────────────────────────────────
# נועד למנוע שגיאות ייבוא (ImportError) מקבצים ישנים כמו fallback.py ו-planner
# ---------------------------------------------------------------------------
fetch_flights = search_outbound_flights
fetch_return_flights = search_return_flights
fetch_hotels = search_hotels
# הוספתי גם את הפעילויות ליתר ביטחון
fetch_activities_alias = search_activities


# ---------------------------------------------------------------------------
# Tool registry — imported by executor.py
# ---------------------------------------------------------------------------
ITINERARY_TOOLS = [
    search_outbound_flights,
    search_return_flights,
    search_hotels,
    search_activities,
    get_weather,
    calculate_trip_cost,
]